name: publish

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cabal sdist

      - uses: sol/test-repo@main
        id: create-tag
        with:
          dry-run: true

      - uses: sol/hackage-publish@dev
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          publish: false
        if: steps.create-tag.outputs.created
