name: publish

on:
  push:
    branches:
      - autotag

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: sol/haskell-autotag@v1
        id: autotag
        with:
          prefix: null
          dry-run: true

      - run: cabal sdist
      - uses: sol/hackage-publish@dev
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          publish: false
        if: steps.autotag.outputs.created
